# Generated by Django 4.1 on 2022-08-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_user_profile_user_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_obj',
        ),
    ]
