# Generated by Django 4.0.4 on 2022-08-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
